on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > php.pem
          chmod 600 php.pem
          SECRET=$(echo "$SSH_PRIVATE_KEY" > php.pem)
          IP_DO_SERVIDOR="4.246.190.23"
          ssh -o StrictHostKeyChecking=no -i php.pem juliobsilva@$IP_DO_SERVIDOR     
         
      - name: Transfer files
        run: |
          sudo scp -o StrictHostKeyChecking=no -i $SECRET -r php_blog/* juliobsilva@4.246.190.23:/var/www/blog/

