name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Configure SSh
              env:
                  SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
                  SSH_KNOW_HOSTS: ${{ secrets.SSH_KNOW_HOSTS }}
              run: |
                  mkdir -p ~/.ssh
                  echo "$SSH_PUBLIC_KEY" > ~/.ssh/id_rsa.pub
                  echo "$SSH_KNOW_HOSTS" > ~/.ssh/known_hosts
                  chmod 700 ~/.ssh
                  chmod 600 ~/.ssh/*

            - name: Transfer files
              run: scp -r php_blog/* root@4.246.190.23:/APP

              

                

          
    