on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > ssh_key
          chmod 600 ssh_key
          IP_DO_SERVIDOR="4.246.190.23"
          ssh -o StrictHostKeyChecking=no -i ssh_key juliobsilva@$IP_DO_SERVIDOR

      - name: Transfer files
        run: |
          sudo scp -o StrictHostKeyChecking=no -i ssh_key -r php_blog/* juliobsilva@4.246.190.23:/var/www/html/
