name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          pwd
          ls -lha
          IP_DO_SERVIDOR="4.246.190.23"         
          ssh -i ~/php.pem juliobsilva@$IP_DO_SERVIDOR

      - name: Transfer files
        run: sudo scp -r php_blog/* juliobsilva@4.246.190.23:/var/www/html/

        