name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ls -lha          
          ssh -i php.pem juliobsilva@4.246.190.23

      - name: Transfer files
        run: sudo scp -r php_blog/* juliobsilva@4.246.190.23:/var/www/html/

        